name: blurly
description: A customizable Flutter widget for creating beautiful glassmorphic blur effects.
version: 0.0.1
repository: https://github.com/tade-dev/blurly
issue_tracker: https://github.com/tade-dev/blurly/issues
documentation: https://github.com/tade-dev/blurly/blob/main/README.md
topics:
  - blur
  - glassmorphism
  - ui
  - widgets
  - effects

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg